- src/screens/CreatePost/elements/SheetMedia.js
- src/screens/CreatePost/index.js
- src/service/topicPages.js
- src/utils/permission/index.js
Reverts BetterSocial/mobileapp#410
> Revert "Ping 1382"

- __tests__/screens/FeedScreen/__snapshots__/ContentLink.test.js.snap
- src/screens/CreatePost/index.js
Reverts BetterSocial/mobileapp#479
> Revert "Release preparation"

- __tests__/screens/FeedScreen/__snapshots__/ContentLink.test.js.snap
- src/navigations/HomeBottomTabs.js
Fixing double dynamic link callback making navigation to other profile called double.
> PING-2433 Link to profile not working.

- src/components/Header/HeaderContact.js
- src/components/Loading/index.js
- src/components/LoadingWithoutModal/index.js
- src/components/Search/SearchContact.js
- src/screens/AddParticipant/index.js
- src/screens/ChannelListScreen/elements/Search.js
- src/screens/ContactScreen/elements/Search.js
- src/screens/ContactScreen/index.js
- src/screens/CreatePost/elements/CreatePollContainer/style/CreatePollContainerBaseStyle.js
- src/screens/DiscoveryScreenV2/elements/Search.js
- src/screens/FeedScreen/elements/Search.js
- src/screens/GroupSetting/elements/EditGroup.js
- src/screens/GroupSetting/index.js
- src/screens/Loading/index.js
- src/screens/NewsScreen/Search.js
- src/utils/colors/index.js
- src/utils/theme/index.js
Decided to ignore duplicate code due to work load, created https://pingsocial.atlassian.net/browse/PING-2902 as reminder to simplify later.
> fix: ping 2899 clean up duplicate colors

- package.json
- src/components/Comments/WriteComment.js
- src/components/ToggleSwitch/index.tsx
- src/screens/CreatePost/elements/UserProfile.js
- src/screens/OtherProfile/index.js
- src/screens/ProfileScreen/elements/BioAndDMSetting.tsx
- yarn.lock
app/assets/30101915/e58ef3f3-a73f-4901-b559-8b9b247e1462)
> feat: ping-2176 change component toggle switch

- __tests__/hooks/useFollowUser.test.js
- src/components/AnonymousChat/BaseChannelItem.tsx
- src/components/AnonymousChat/MessageChannelItem.tsx
- src/components/AnonymousChat/child/ChannelFollowButton.tsx
- src/components/AnonymousChat/child/ChannelTitle.tsx
- src/components/HorizontalTab/index.tsx
- src/database/atom/migrationDbStatusAtom.ts
- src/database/hooks/useLocalDatabaseHook.js
- src/database/migration/index.ts
- src/database/schema/ChatSchema.ts
- src/hooks/core/useCoreChatSystemHook.ts
- src/screens/ChannelListScreen/hooks/useFollowUser.ts
- src/screens/ChannelListScreen/index.tsx
- src/screens/ChannelListScreenV2/AnonymousChannelListScreen/index.tsx
- src/screens/ChannelListScreenV2/index.tsx
- types/component/AnonymousChat/BaseChannelItem.types.ts
- types/component/AnonymousChat/MessageChannelItem.types.ts
- types/database/schema/ChannelList.types.ts
Please review the latest commit to save your time. Other commits have been reviewed on [#1495](https://github.com/BetterSocial/mobileapp/pull/1495)
> feat: ping 2740 chattab follow

- src/screens/WhotoFollow/index.js
The problem occurs because the photo upload has not been completed but the user has registered and is redirected to the next page. So currently the solution is to wait for the photo upload to finish before registering. If there are no changes to the photo then register immediately
> PING-2996 fix: logic register user with/without change user photo profile

- src/configs/FirebaseConfig.js
> feat: add dynamic link from send anon web app

- ios/Podfile.lock
- src/screens/FeedScreen/hooks/useCoreFeed.js
- src/screens/FeedScreen/hooks/useViewPostTimeHook.ts
- src/screens/TopicPageScreen/index.js
Only for sonarcloud and guardrails check
> feat: add view post time functionality in topic feeds

- __tests__/database/migration/file/index.test.ts
- __tests__/database/migration/index.test.ts
- src/database/hooks/useLocalDatabaseHook.js
- src/database/migration/file/index.ts
- src/database/migration/file/migration_version_10_users_add_anon_user_info_color_name.ts
- src/database/migration/file/migration_version_11_users_add_anon_user_info_color_code.ts
- src/database/migration/file/migration_version_12_channel_lists_add_anon_user_info_emoji_name.ts
- src/database/migration/file/migration_version_13_channel_lists_add_anon_user_info_emoji_code.ts
- src/database/migration/file/migration_version_14_channel_lists_add_anon_user_info_color_name.ts
- src/database/migration/file/migration_version_15_channel_lists_add_anon_user_info_color_code.ts
- src/database/migration/file/migration_version_16_users_add_anon_user_info_emoji_name.ts
- src/database/migration/file/migration_version_8_change_enum_to_text.ts
- src/database/migration/file/migration_version_9_users_add_anon_user_info_emoji_code.ts
- src/database/migration/index.ts
This commits include:
1. Add several new migrations to contain anon user info
2. Change target migration version
3. Adjust test suite related to migration
4. Add new checks for useLocalDatabaseHook
> feat: migration for fixing emoji

- src/components/Button/Button.js
- src/navigations/root-stack.js
- src/screens/CreatePost/elements/SheetCloseBtn.js
- src/screens/DiscoveryScreenV2/fragment/DomainFragment.js
- src/screens/DiscoveryScreenV2/fragment/TopicFragment.js
- src/screens/DiscoveryScreenV2/fragment/UsersFragment.js
- src/screens/Followings/index.js
- src/screens/ProfileScreen/elements/BottomSheetBio.js
on this PR
1. fix safe area view on follower screen
after: 
2. fix tap behavior on discovery, following, and follower
before: https://helioapp.slack.com/archives/C065C3K659Q/p1705548872139979
https://github.com/BetterSocial/mobileapp/assets/13555051/6610494f-65fc-4328-8707-0999d4462489
3. fix discard post style
before: https://pingsocial.atlassian.net/browse/PING-3434
4. fix edit prompt style
before: https://pingsocial.atlassian.net/browse/PING-3434
> fix: discovery tap behavior and safe area follower

- __tests__/screens/FeedScreen/__snapshots__/ContentLink.test.js.snap
- src/components/Comments/WriteComment.js
- src/components/PostPageDetail/index.js
- src/components/ToggleSwitch/index.tsx
- src/screens/FeedScreen/Content.js
- src/screens/FeedScreen/ContentLink.js
- src/screens/FeedScreen/RenderList.js
- src/screens/FeedScreen/index.js
- src/screens/OtherProfile/index.js
- src/screens/OtherProfilePostDetail/index.js
- src/screens/PostPageDetail/index.js
- src/screens/ProfileScreen/elements/RenderItem.js
- src/screens/ProfileScreen/index.js
- src/screens/TopicPageScreen/MemoizedListComponent.js
- src/screens/TopicPageScreen/index.js
> feat: add feed preview comment

- __tests__/components/Comments/WriteComment.test.js
- __tests__/screens/FeedScreen/__snapshots__/ContentLink.test.js.snap
- __tests__/screens/FeedScreen/__snapshots__/ContentPoll.test.js.snap
- src/components/Card/Card.js
- src/components/Comments/WriteComment.js
- src/components/TopicsChip/TopicsChip.js
- src/screens/FeedScreen/Content.js
- src/screens/FeedScreen/ContentLink.js
- src/screens/FeedScreen/ContentPoll.js
- src/screens/FeedScreen/RenderList.js
- src/screens/FeedScreen/elements/BlurredLayer.js
- fix blurred layer and preview comment conflict on feed that make some post overlapping other component
- refactor post component, [visualization](https://excalidraw.com/#room=27242ade8a81af46bac3,Cx9Ha3ZAjY4aq_hjMb3wig)
> fix: blurred layer and preview comment on feed

- src/components/PreviewComment/index.js
- src/screens/FeedScreen/Header.js
- src/screens/ProfileScreen/elements/ProfilePicture.js
> fix: ping-3646 karma anon missing

- src/components/Comments/ContainerComment.js
- src/screens/FeedScreen/RenderList.js
- src/screens/FeedScreen/elements/AddCommentPreview.tsx
- src/screens/TopicPageScreen/MemoizedListComponent.js
- fix topic feed add preview comment for showing when post is blurred
- fix topic feed preview comment not showing on post that have more than 1 comment
> fix: topic feeds comment

- src/navigations/root-stack.js
- src/screens/DiscoveryScreenV2/elements/Search.js
- src/screens/DiscoveryScreenV2/index.js
https://github.com/BetterSocial/mobileapp/assets/13555051/5686b2a4-cbf4-4fc3-a729-1dd6bd94cdbd
> fix: ping-3480 Going back to discovery doesnt save position/search

- __tests__/components/PreviewComment/PreviewComment.test.js
- src/screens/Blocked/elements/DomainScreen/index.js
- src/screens/Blocked/elements/UserScreen/index.js
- src/screens/Blocked/index.js
> fix: ping-3673 blocked list layout

- __tests__/components/Comments/WriteComment.test.js
- src/components/Comments/WriteComment.js
- src/screens/FeedScreen/Content.js
- src/screens/FeedScreen/ContentPoll.js
- src/screens/FeedScreen/RenderList.js
- src/screens/TopicPageScreen/MemoizedListComponent.js
- src/screens/TopicPageScreen/elements/NavHeader.js
- fix topic chips style (https://pingsocial.atlassian.net/browse/PING-3692)
- fix preview comment on reply view page
- fix community nav header
> [PING-3692][PING-3645] fix: render feed feedback

- src/hooks/core/useCoreChatSystemHook.ts
- src/libraries/reactotron/reactotronInstance.js
- src/screens/CreatePost/index.js
- src/utils/constants/index.js
- src/utils/getstream/useChatClientHook.js
- src/utils/string/StringUtils.js
- types/repo/ChannelData.ts
Since the fixes are on the core system, not much UI changes will be affected
> fix: remove setting image when following and creating post

- src/components/Chat/InputMessageV2.tsx
- src/hooks/useToggleColors.js
- src/screens/CreatePost/elements/UserProfile.js
- src/screens/OtherProfile/elements/BioAndChat.js
> [PING-3628] fix: toggle anon

- src/utils/constants/index.js
> fix: change feed diff value to fetch

- android/app/build.gradle
- src/screens/FeedScreen/Content.js
- src/screens/FeedScreen/hooks/useViewPostTimeHook.ts
> fix: hotfix 2.10.1

- src/screens/TopicPageScreen/index.js
> [PING-3224] fix: community search mismatch data

- __tests__/components/AnonymousChat/child/__snapshots__/ChatItemMyTextV2.test.tsx.snap
- src/components/AnonymousChat/child/ChatItemMyTextV2.tsx
- src/components/Chat/BottomSheetGif.js
- src/service/gif.js
- src/utils/permission/index.js
Jira Link: https://pingsocial.atlassian.net/browse/PING-3711
> fix: ping 3711 search gif broken

- src/components/TextAreaChat/index.tsx
- x ] Pastikan untuk mengikuti [guidelines pembuatan komponen Guidelines About Loading and Layout](https://docs.google.com/document/d/1GHbvEtFrQmEQXYBV9dLrPI654n2DbPwS1qjedajLSiw/edit)
> fix: ping-3762 weird auto fill on other profile

- src/hooks/screen/useCreateChat.ts
- src/screens/OtherProfile/index.js
> feat: ping-3757 other profile doesnt allow incognito messages

- src/screens/GroupInfo/elements/ModalAction.js
> [PING-3758] fix: popup to fast

- src/hooks/core/chat/useFetchChannelHook.ts
> fix: system message from registration

- src/screens/FeedScreen/Header.js
> fix: padding header anon

- src/components/Footer/Footer.js
- src/screens/FeedScreen/Header.js
- src/screens/OtherProfile/index.js
- src/screens/ProfileScreen/elements/RenderItem.js
- src/screens/TopicPageScreen/MemoizedListComponent.js
- src/screens/TopicPageScreen/index.js
> fix: dm and follow from topic pages

- src/screens/TopicMemberScreen/index.js
> [PING-3545] fix: topic memberlist scrolling weird

- src/screens/ProfileScreen/elements/FollowInfoRow.js
- src/screens/ProfileScreen/index.js
> fix: ping-3807 padding bellow dp

- src/screens/ProfileScreen/index.js
> fix: ping-3777 view dp not working

- src/screens/ProfileScreen/elements/ProfilePicture.js
> fix: ping-3776 change resize mode from stretch to cover

- src/screens/ChatScreen/AnonymousChatScreen.tsx
> fix: change system message anon chat

- src/screens/FeedScreen/RenderList.js
> fix: issue when click from pressComment

- src/hooks/core/chat/useChatUtilsHook.ts
- src/hooks/screen/useChatScreenHook.ts
> feat: fix back after switching chat from chat info screen

- src/utils/string/StringUtils.js
> fix: PING-3778 add hashtag after fallback topic name value

- src/screens/ProfileScreen/elements/LinkAndSocialMedia.tsx
> feat: ping-3806 fix share button

- __tests__/components/AnonymousChat/child/__snapshots__/ChatItemTargetText.test.tsx.snap
- src/components/AnonymousChat/BaseChatItem.tsx
- src/components/AnonymousChat/child/ChatItemAttachment.tsx
- src/components/AnonymousChat/child/ChatItemAttachmentStyles.tsx
- src/components/AnonymousChat/child/ChatItemMyTextV2.tsx
- src/components/AnonymousChat/child/ChatItemTargetText.tsx
> fix: ping 3826 media not showing up on recipient side main

- ios/Podfile.lock
- package.json
- src/screens/ProfileScreen/elements/BioAndDMSetting.tsx
- src/screens/ProfileScreen/elements/TextWithEmoji.tsx
- yarn.lock
> fix: ping-3752 profile bio font style wrong

- src/components/Header/index.js
> feat: ping-3753 center headlines

- src/components/Comments/Comment.js
- src/components/Comments/ReplyCommentItem.js
> fix: hide block button if my comment and my post

- src/components/PostPageDetail/index.js
- src/screens/ChannelListScreen/index.tsx
- src/screens/ChannelListScreenV2/AnonymousChannelListScreen/index.tsx
- src/screens/FeedScreen/Header.js
- src/screens/FeedScreen/hooks/useFeedHeader.js
- src/screens/FeedScreen/index.js
> feat: release 3504-3582-3754

- src/screens/ProfileScreen/elements/AnonymousTab.js
- src/screens/ProfileScreen/index.js
> fix: change anonymous tab color in profile to anonprimary

- src/screens/ProfileScreen/elements/ProfilePicture.js
> feat: ping-3712 dp not center

- src/screens/DiscoveryScreenV2/elements/RecentSearch.js
> fix: ping-3834 discovery recent in wrong color

- src/components/PostPageDetail/index.js
> fix: upvote refresh

- src/components/PostPageDetail/elements/Content.js
> fix: missing color when open pdp from notif

- src/components/PostPageDetail/index.js
- src/screens/FeedScreen/Header.js
- src/screens/FeedScreen/hooks/useFeedHeader.js
- src/screens/FeedScreen/index.js
- src/screens/PostPageDetail/index.js
> fix: pdp always back to feeds + release fix 3705

- ios/Helio.xcodeproj/project.pbxproj
- ios/PrivacyInfo.xcprivacy
> Core - Add Privacy Info to fix warning on App Store

- src/database/hooks/useLocalDatabaseHook.js
- src/hooks/core/chat/useChatUtilsHook.ts
- src/hooks/core/chat/useFetchChannelHook.ts
- src/hooks/core/chat/useFetchPostNotificationHook.ts
- src/hooks/screen/useChatScreenHook.ts
- src/hooks/useInitialStartup.js
- src/screens/ChatScreen/SignedChatScreen.tsx
- src/service/repo/anonymousMessageRepo.ts
- src/service/repo/signedMessageRepo.ts
- src/utils/storage/index.ts
- src/utils/users/index.js
> feat: add timestamp request API

- __tests__/hooks/useFeedHeader.test.js
- __tests__/screens/FeedScreen/HeaderFeed.test.js
> test: fix unit test on main

- ios/PrivacyInfo.xcprivacy
> chore: update privacy setting

- src/screens/CreatePost/index.js
> [PING-3675] fix: post got error message but success create

- src/core/queue/BaseQueue.ts
> fix: base queue property

- src/screens/CreatePost/index.js
> fix: ping-3876 crash start posting

- src/components/Comments/Comment.js
- src/components/Comments/ContainerComment.js
- src/components/Comments/ListComment.js
- src/components/Comments/ReplyCommentItem.js
- src/components/ReplyComment/index.js
- src/hooks/core/chat/useDMMessage.ts
- src/service/chat.js
> feat: add dm from comments

- src/hooks/core/push-notification/usePushNotificationHook.ts
- src/service/repo/messageRepo.ts
> feat: ping-3895 background message handler

- __tests__/screens/FeedScreen/__snapshots__/ContentLink.test.js.snap
- src/components/Footer/Footer.js
- src/screens/FeedScreen/Content.js
- src/screens/FeedScreen/ContentLink.js
- src/screens/FeedScreen/Header.js
- src/screens/FeedScreen/RenderList.js
- src/screens/OtherProfile/index.js
- src/screens/ProfileScreen/elements/RenderItem.js
> [PING-3822] fix: other profile feed staging

- __tests__/screens/FeedScreen/__snapshots__/ContentLink.test.js.snap
- src/components/Footer/Footer.js
- src/screens/FeedScreen/Content.js
- src/screens/FeedScreen/ContentLink.js
- src/screens/FeedScreen/Header.js
- src/screens/FeedScreen/RenderList.js
- src/screens/OtherProfile/index.js
- src/screens/ProfileScreen/elements/RenderItem.js
> [PING-3822] fix: other profile feed

- __tests__/components/Comments/ConnectorWrapper.test.js
- src/assets/icon/IconChevronLeft.tsx
- src/assets/timer/EightyEight_hundred.js
- src/assets/timer/Fivety_sixtyTwo.js
- src/assets/timer/One.js
- src/assets/timer/SeventyFive_eightySeven.js
- src/assets/timer/SixtyThree_seventyFour.js
- src/assets/timer/ThirtySeven_fourtyNine.js
- src/assets/timer/TwentyFive_thirtySix.js
- src/assets/timer/Zero_twentyFour.js
- src/components/Comments/Comment.js
- src/components/Comments/ConnectorWrapper.js
- src/components/Comments/ContainerComment.js
- src/components/PostPageDetail/elements/Content.js
- src/components/PostPageDetail/index.js
- src/screens/FeedScreen/Header.js
- src/screens/FeedScreen/RenderList.js
- src/screens/FeedScreen/index.js
> [PING-3822] feat: post detail page redesign

- __tests__/database/schema/ChatSchema.test.ts
- src/database/schema/ChatSchema.ts
> fix: ping-3926 message double/redundant on anon to anon message

- src/components/Comments/Comment.js
- src/components/Comments/ReplyCommentItem.js
- src/components/Footer/Footer.js
- src/utils/theme/index.js
> [PING-3925] fix: vote color

- src/hooks/core/push-notification/usePushNotificationHook.ts
> fix: ping-3934 ping-3935 pn on app open and open when receiver anon

- src/hooks/core/push-notification/usePushNotificationHook.ts
> fix: no need to fetch channel detail when open chat from push notif

- src/hooks/core/push-notification/usePushNotificationHook.ts
> feat: ping-3969 remove pn are read already

- ios/Helio.xcodeproj/project.pbxproj
- ios/Podfile.lock
- package.json
- src/hooks/context/useResetContext.js
- src/screens/TopicPageScreen/index.js
- yarn.lock
> fix: upgrade async storage to prevent crash

- __tests__/hooks/useSettings.test.js
- src/screens/Settings/hooks/useSettings.js
- src/service/users.js
> fix: change fcm token delete url to v2

- src/screens/GroupInfo/elements/ModalAction.js
> fix: move to signed message from detail

- ios/Podfile.lock
- package.json
- src/screens/SignInV2/index.js
- yarn.lock
> chore: upgrade human ID version to 2.4.11

- __tests__/components/Comments/WriteComment.test.js
- src/components/Comments/WriteComment.js
- src/components/PostPageDetail/index.js
- src/service/comment.js
> [PING-3850] fix: write comment and comment style

- src/components/CommentUsername/CommentUsername.js
- src/components/Comments/Comment.js
> [PING-3849] fix: comment text behavior

- App.js
- ios/Podfile.lock
- package.json
- src/hooks/screen/services/chatScreenHooks.js
- src/hooks/screen/useChatScreenHook.ts
- src/screens/ChatScreen/SignedChatScreen.tsx
- types/hooks/screens/useChatScreenHook.types.ts
- yarn.lock
> fix: ping-3966 chat screen is loading slow, and reloading every time i go to the chat

- src/screens/ProfileScreen/elements/KarmaLock.tsx
> feat: ping-3996 my profile not aligned

- src/screens/Settings/index.js
> fix: enable news on settings

- src/components/Comments/ContainerComment.js
> [PING-3732] fix: remove connector last comment

- src/components/CredderRating/FeedCredderRating.js
- src/components/PostPageDetail/elements/Content.js
> [PING-3607] fix: credder score pdp

- src/core/queue/DatabaseQueue.ts
- src/database/schema/ChannelListSchema.ts
- src/hooks/appBadge/useAppBadgeHook.ts
- src/hooks/core/push-notification/usePushNotificationHook.ts
- src/hooks/core/useCoreChatSystemHook.ts
- src/navigations/HomeBottomTabs.js
> feat: add badge number on home

- src/navigations/HomeBottomTabs.js
> fix: change bottom tab name

- src/screens/DiscoveryScreenV2/fragment/TopicFragment.js
- src/screens/DiscoveryScreenV2/fragment/UsersFragment.js
- src/screens/DiscoveryScreenV2/hooks/useDiscovery.js
- src/screens/DiscoveryScreenV2/index.js
- src/screens/OtherProfile/index.js
- src/screens/TopicPageScreen/elements/BottomSheetFollow.tsx
- src/screens/TopicPageScreen/index.js
> fix: join state between discovery and profile

- src/components/DevDummyLogin/index.js
- src/service/users.js
> fix: change demo verify user endpoint

- src/components/ReadMore/index.js
- src/screens/ProfileScreen/elements/TextWithEmoji.tsx
> [PING-3950] fix: comment preview if emoji

- src/screens/TopicPageScreen/elements/NavHeader.js
- src/screens/TopicPageScreen/index.js
> [PING-3556] fix: community page header design

- ios/PrivacyInfo.xcprivacy
> fix: fix wrong privacy info

- src/screens/TopicPageScreen/elements/NavHeader.js
- src/screens/TopicPageScreen/index.js
> [PING-4045] fix: no safe area cp member list

- src/screens/DiscoveryScreenV2/elements/Search.js
- src/screens/DiscoveryScreenV2/fragment/NewsFragment.js
- src/screens/DiscoveryScreenV2/fragment/TopicFragment.js
- src/screens/DiscoveryScreenV2/fragment/UsersFragment.js
- src/screens/DiscoveryScreenV2/index.js
> feat: adjust keyboard behaviours discovery page

- .babelrc
- babel.config.js
- ios/Helio.xcodeproj/project.pbxproj
- ios/Podfile.lock
- package.json
- src/libraries/Configs/ENVConfig.js
- src/libraries/analytics/analyticsEventTracking.ts
- src/screens/InputUsername/index.js
- src/screens/LocalCommunity/index.js
- src/screens/SignInV2/index.js
- src/screens/Topics/ListTopics.js
- src/screens/Topics/index.js
- src/screens/WhotoFollow/index.js
- yarn.lock
> feat: add segment sdk and add tracking on human id action

- __tests__/screens/FeedScreen/__snapshots__/ContentLink.test.js.snap
- src/components/Card/Card.js
- src/components/PostPageDetail/elements/Content.js
- src/screens/FeedScreen/Content.js
- src/screens/FeedScreen/ContentLink.js
- src/screens/FeedScreen/hooks/useCalculationContent.js
> [PING-3970] fix: font size cut off

- __tests__/components/AnonymousChat/child/__snapshots__/ChatItemMyTextV2.test.tsx.snap
- __tests__/components/AnonymousChat/child/__snapshots__/ChatItemTargetText.test.tsx.snap
- src/components/AnonymousChat/child/ChatItemMyTextV2.tsx
- src/components/AnonymousChat/child/ChatItemTargetText.tsx
- src/components/LinkableText.tsx
- src/hooks/core/websocket/useSimpleWebsocketHooks.tsx
- src/utils/theme/index.js
> feat: ping-3988 clickable link messge

- ios/Helio.xcodeproj/project.pbxproj
- src/components/LinkableText.tsx
- src/screens/OtherProfile/elements/BioAndChat.js
- src/screens/ProfileScreen/elements/TextWithEmoji.tsx
- src/utils/string/StringUtils.js
> feat: add link detection on bio

- ios/BetterSocial/Images.xcassets/AppIcon.appiconset/Contents.json
> fix: fix failed send to app store

- src/database/schema/ChatSchema.ts
- src/hooks/screen/useChatScreenHook.ts
- src/navigations/root-stack.js
- src/screens/ChatScreen/AnonymousChatScreen.tsx
- src/screens/ChatScreen/SignedChatScreen.tsx
- src/service/chat.js
- types/hooks/screens/useChatScreenHook.types.ts
> feat: ping-4044 retry send pending message

- src/screens/DiscoveryScreenV2/elements/Search.js
> fix: add force search when press search button on keyboard

- __tests__/screens/FeedScreen/__snapshots__/ContentLink.test.js.snap
- src/components/Card/Card.js
- src/components/Card/CardHeader.js
- src/screens/FeedScreen/ContentLink.js
> fix: change news date

- src/libraries/analytics/analyticsEventTracking.ts
- src/screens/InputUsername/index.js
- src/screens/LocalCommunity/index.js
- src/screens/Topics/index.js
> fix: PING-4095 adjust some analytics events on onboarding

- __tests__/components/AnonymousChat/child/ChatItemMyTextV2.test.tsx
- __tests__/components/AnonymousChat/child/ChatItemTargetText.test.tsx
- __tests__/components/AnonymousChat/child/__snapshots__/ChatItemMyTextV2.test.tsx.snap
- __tests__/components/AnonymousChat/child/__snapshots__/ChatItemTargetText.test.tsx.snap
- ios/Podfile.lock
- package.json
- src/components/AnonymousChat/child/ChatItemMyTextV2.tsx
- src/components/AnonymousChat/child/ChatItemTargetText.tsx
- src/components/ContextMenuView/ChatContextMenuView.tsx
- src/utils/share/index.js
- yarn.lock
> feat: enable longpress copy on chat

- src/screens/FeedScreen/Header.js
- src/screens/ProfileScreen/index.js
> fix: unable to delete post on profile screen

- __tests__/components/AnonymousChat/child/__snapshots__/ChatItemMyTextV2.test.tsx.snap
- __tests__/components/AnonymousChat/child/__snapshots__/ChatItemTargetText.test.tsx.snap
- src/components/AnonymousChat/child/ChatItemMyTextV2.tsx
- src/components/AnonymousChat/child/ChatItemTargetText.tsx
- src/components/Text/LinkDetectionText.tsx
- src/screens/OtherProfile/elements/BioAndChat.js
> fix: link detection on my chat item and target chat item

- src/components/ChatList/CommunityChannelItem.tsx
- src/components/ChatList/elements/ChannelImage.style.ts
- src/components/ChatList/elements/ChannelImage.tsx
- src/hooks/screen/useAnonymousChannelListHook.ts
- src/screens/ChannelListScreenV2/AnonymousChannelListScreen/index.tsx
- types/component/ChatList/ChannelImage.types.ts
- types/database/schema/ChannelList.types.ts
- types/hooks/screens/useAnonymousChannelListScreenHook.types.ts
> [PING-4120] fix: community icon on chat tab

- src/screens/DiscoveryScreenV2/fragment/UsersFragment.js
- src/screens/TopicMemberScreen/index.js
> feat: collapsible in community member list

- src/screens/DiscoveryScreenV2/elements/DiscoveryItemList.js
- src/screens/DiscoveryScreenV2/fragment/UserFragmentCommunity.js
- src/screens/TopicMemberScreen/index.js
> [PING-4154] feat: show profile on topic member list

- src/screens/CreatePost/index.js
> fix: crash when start posting from other profile

- __tests__/service/onesignal/OneSignalUtil.test.ts
- src/service/onesignal/index.ts
> fix: add hasUserPosted on onesignal subscribtion

- src/navigations/root-stack.js
- src/screens/TopicMemberScreen/index.js
- src/screens/TopicPageScreen/elements/NavHeader.js
- src/screens/TopicPageScreen/index.js
> [PING-4157] fix: glitch community member list

- src/screens/DiscoveryScreenV2/fragment/UsersFragment.js
> fix: userfragment not open by default

- src/screens/TopicPageScreen/index.js
> [PING-4153] fix: shimmer on topic page member count

- src/screens/TopicMemberScreen/index.js
> [PING-4165] fix: rollback show own profile in topic member list

- src/screens/TopicPageScreen/index.js
> [PING-4153] fix: add shimmer on topic member count

- src/screens/CreateCommunity/index.js
> fix: disabled v3 create community for release new prod version

- src/screens/Followings/FollowersScreen.js
- src/screens/Followings/index.js
- src/screens/ProfileScreen/index.js
> [PING-4162] feat: separate follower list

- src/components/AnonymousChat/BaseChannelItem.tsx
- src/components/AnonymousChat/MessageChannelItem.tsx
- src/components/AnonymousChat/child/ChannelTitle.tsx
- src/components/Chat/InputMessageV2.tsx
- types/component/AnonymousChat/BaseChannelItem.types.ts
> feat: change emoji to chat description title

- src/screens/CreatePost/index.js
- src/screens/ProfileScreen/index.js
> fix: create post from karma lock component

- src/components/ChatList/GroupChatChannelItem.tsx
- src/database/schema/ChannelListSchema.ts
- src/hooks/core/websocket/types.d.ts
- types/component/ChatList/ChannelContent.types.ts
- types/database/schema/ChannelList.types.ts
> feat: add preview on channel list when changing group name

- src/hooks/core/push-notification/usePushNotificationHook.ts
> fix: add notification.data.type topic to handle notification

- __tests__/service/anonymousMessageRepo.test.ts
- src/components/AnonymousChat/BaseChannelItem.tsx
- src/components/AnonymousChat/PostNotificationChannelItem.tsx
- src/components/AnonymousChat/child/ChannelTitle.tsx
- src/service/feeds.js
- src/service/repo/anonymousMessageRepo.ts
- src/service/repo/signedMessageRepo.ts
- types/component/AnonymousChat/BaseChannelItem.types.ts
> feat: italic media for post that has images and no messages

- src/navigations/root-stack.js
- src/screens/ChatScreen/AnonymousChatScreen.tsx
- src/screens/ChatScreen/ChatScreen.styles.tsx
- src/screens/ChatScreen/SignedChatScreen.tsx
- src/screens/ChatScreen/useChatScreenDimensions.tsx
- src/screens/TopicPageScreen/elements/NavHeader.js
> fix: change margin top condition for nav header

- src/atom/currentChatScreenAtom.ts
- src/hooks/core/push-notification/usePushNotificationHook.ts
- src/hooks/screen/useChatScreenHook.ts
> fix: push notification case not opening correct chat screen

- src/screens/DiscoveryScreenV2/fragment/DomainFragment.js
- src/screens/DomainScreen/index.js
> fix: domain follow and count issue PING-4228 and PING-4234

- src/screens/DiscoveryScreenV2/fragment/TopicFragment.js
> fix: join topic button PING-4224

- src/hooks/useInitialStartup.js
> fix: slow loading topic PING-4158

- src/screens/DiscoveryScreenV2/fragment/TopicFragment.js
> fix: cannot scroll to the end of communities list PING-4252

- src/components/PreviewComment/index.js
- src/screens/FeedScreen/elements/AddCommentPreview.tsx
- src/screens/FeedScreen/index.js
> [PING-2321] fix: scrolling height improvement

- src/screens/FeedScreen/Content.js
> fix: mode cover if multiple images post PING-4272

- __tests__/context/reducers/localCommunityReducer.test.js
- src/context/reducers/localComunityReducer.js
- src/screens/InputUsername/index.js
- src/screens/SignInV2/elements/SlideShow.js
- src/screens/Topics/index.js
> feat: remove location screen from the onboarding

- src/hooks/core/onesignal/types.d.ts
- src/hooks/core/onesignal/useOneSignalSubscribeToCommunityHooks.ts
- src/hooks/core/push-notification/usePushNotificationHook.ts
- src/libraries/analytics/analyticsEventTracking.ts
- src/screens/OtherProfile/hooks/useOtherProfileScreenHooks.tsx
- src/utils/constants/index.js
> feat: onesignal push notifications open and analytics

- src/components/PostPageDetail/elements/Content.js
> [PING-4319] fix: pdp image height

- src/components/Footer/Footer.js
> [PING-4330] fix: dm anon not working

- src/components/PostPageDetail/index.js
- src/screens/TopicPageScreen/index.js
> fix: undefined link when sharing in post detail page

- src/components/Footer/Footer.js
- src/database/schema/ChannelListSchema.ts
- src/hooks/core/chat/useDMMessage.ts
- src/hooks/core/chat/useSystemMessage.ts
- src/screens/TopicPageScreen/MemoizedListComponent.js
> fix: dm from post not working

- ios/BetterSocialStaging/Info.plist
- src/libraries/analytics/analyticsEventTracking.ts
> fix: segment and mixpanel singleton and set identity

- src/components/AnonymousChat/BaseChatItem.tsx
- src/components/AnonymousChat/child/ChatItemMyTextV2.tsx
- src/components/AnonymousChat/child/ChatItemTargetText.tsx
- src/components/ContextMenuView/ChatContextMenuView.tsx
- src/hooks/core/chat/useMessageHook.ts
- types/component/AnonymousChat/BaseChannelItem.types.ts
- types/component/AnonymousChat/BaseChatItem.types.ts
> fix: delete anon chat

- src/components/AnonymousChat/BaseChannelItem.tsx
- src/components/AnonymousChat/BaseChannelItemStyles.tsx
- src/components/AnonymousChat/MessageChannelItem.tsx
- src/components/AnonymousChat/PostNotificationChannelItem.tsx
- src/components/ChatList/ChannelItem.style.ts
- src/components/ChatList/CommunityChannelItem.tsx
- src/components/ChatList/GroupChatChannelItem.tsx
- src/utils/theme/index.js
- types/component/AnonymousChat/BaseChannelItem.types.ts
> feat: add channel background color depending on channelType

- src/components/PostPageDetail/index.js
> fix: share button in own anon post

- src/components/PostPageDetail/elements/Content.js
> fix: post text in pdp expanded
